config/routes.rb
Rails.application.routes.draw do
  get 'favorites/new'

  get 'favorites/destroy'

  get 'genre/index'

  get 'genre/show'

  get 'musics/new'

  get 'landing/index'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users

  resources :musics

  resources :genre

  get 'landing' => 'landing#index'

  controller :sessions do
    post 'login' => :create
    get 'login' => :new
    delete 'logout' => :destroy
  end

  controller :users do
    get 'register' => :new
    get 'settings' => :update
  end

  controller :musics do
    get 'upload' => :new
  end
  controller :genre do
    get 'browse' => :index
  end

  root 'landing#index'

end

app/models/favorites.rb
class Favorites < ActiveRecord::Base
  has_many :musics
end

app/models/genres.rb
class Genres < ActiveRecord::Base
  attr_accessor :ifFavorite
  has_many :music
end

app/models/music.rb
class Music < ActiveRecord::Base
  belongs_to :genres
  has_many :favorites
  attr_accessor :ifFavorite

  validates :title,
            presence: true,
            allow_blank: false
  validates :interpret,
            presence: true,
            allow_blank:false
  validates :path,
            presence: true,
            allow_blank: false
  validates :genre_id,
            presence: true,
            allow_blank: false

  mount_uploader :path, MusicUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email,
            format:/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,
            uniqueness: true
  validates :username,
             uniqueness: true
end

app/controllers/application_controller.rb
#encoding: utf-8
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authorize
  protected
  def authorize
    unless User.find_by(id: session[:user_id])
      redirect_to login_url, notice: 'bitte loggen sie sich ein'
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def new
    @favorite = Favorites.where(user_id: session[:user_id],music_id: params[:music_id])
    if @favorite.any? == false
      @favorite = Favorites.new(user_id: session[:user_id],music_id: params[:music_id])
      if @favorite.save
        respond_to do |format|
          format.js
        end
      end
    end
  end
  def destroy
    Favorites.destroy_all(user_id: session[:user_id],music_id: params[:music_id])
  end
end

app/controllers/genre_controller.rb
class GenreController < ApplicationController
  def index
    @genres = Genres.all
  end

  def show
    if params[:genre_id] == 'all'
      @favorites = Favorites.where(user_id: session[:user_id])

      favoriteMusic = []
      @favorites.each do |favorite|
        favoriteMusic.push(favorite.music_id)
      end
      @musicFavoured = Music.where(id: favoriteMusic)
      @musicUnfavoured = Music.where.not(id: favoriteMusic)
      @musicFavoured.each do |favorite|
        favorite.ifFavorite = true
      end
      @musicUnfavoured.each do |favorite|
        favorite.ifFavorite = false
      end
      @music = (@musicFavoured + @musicUnfavoured).sort_by(&:title)
    else
      @favorites = Favorites.where(user_id: session[:user_id])

      favoriteMusic = []
      @favorites.each do |favorite|
        favoriteMusic.push(favorite.music_id)
      end
      @musicFavoured = Music.where(id: favoriteMusic, genre_id: params[:genre_id])
      @musicUnfavoured = Music.where.not(id: favoriteMusic).where(genre_id: params[:genre_id])
      @musicFavoured.each do |favorite|
        favorite.ifFavorite = true
      end
      @musicUnfavoured.each do |favorite|
        favorite.ifFavorite = false
      end
      @music = (@musicFavoured + @musicUnfavoured).sort_by(&:title)
    end
  end
end

app/controllers/landing_controller.rb
# encoding: utf-8

class LandingController < ApplicationController
  def index
    @favorites = Favorites.where(user_id: session[:user_id])

    favoriteMusic = @favorites.map do |favorite|
      favorite.music_id
    end
    @music = Music.where(id: favoriteMusic)
  end
end

app/controllers/musics_controller.rb
#encoding: utf-8
class MusicsController < ApplicationController
  def new
    @music = Music.new
  end
  def create
    @music = Music.new(music_params)

    respond_to do |format|
      if @music.save
        format.html { redirect_to landing_index_path, alert: 'Deine Musik wurde erfolgreich hochgeladen!' }
        format.json { render :show, status: :created, location: @music }
      else
        format.html { redirect_to upload_path, alert: 'Ups! Irgentwas ging schief :( überprüfe nochmal deine eingaben'}
      end
    end
  end
  def music_params
    params.require(:music).permit(:title, :interpret, :path, :genre_id)
  end
end

app/controllers/sessions_controller.rb
#encoding: utf-8
class SessionsController < ApplicationController
  skip_before_action :authorize

  def new
  end

  def create
    user = User.find_by_username(params[:username])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to landing_url
    else
      redirect_to login_url, alert: "Falscher Username oder Passwort"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_url, alert: "Erfolgreich ausgeloggt!"
  end
end

app/controllers/users_controller.rb
#encoding: utf-8
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:new, :create, :index]


  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to sessions_new_path, alert: 'Dein Account wurde erfolgreich eingerichtet!' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { redirect_to new_user_path, alert: 'Ups! Irgentwas ging schief :( überprüfe nochmal deine eingaben'}
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to landing_index_path, alert: 'Einstellungen wurden erfolgreich gespeichert!' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { redirect_to edit_user_path, alert: 'Bitte alle Felder ausfüllen!'}
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genre_helper.rb
module GenreHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/favorites/new.html.erb
<h1>Favorites#new</h1>
<p>Find me in app/views/favorites/new.html.erb</p>

app/views/favorites/new.js.erb
$("#favorites_<%= @favorite.music_id %>").html($("<%=j link_to '',favorites_destroy_path(:music_id => @favorite.music_id),{ :class =>'icon-heart active', :remote => true} %>"));
$('.icon-heart').hover(function () {
    if ($(this).hasClass('active')) {
        if ($(this).hasClass('icon-heart')) {
            $(this).removeClass('icon-heart');
            $(this).addClass('icon-heart-broken');
        } else {
            $(this).removeClass('icon-heart-broken');
            $(this).addClass('icon-heart');
        }
    }
    $('.icon-heart-broken').click(function () {
        $(this).parents('tr').remove();
    });
});

app/views/genre/index.html.erb
<%= render 'templates/nav' %>

<div id="content">
    <%= render 'templates/genres' %>
</div>

app/views/genre/show.html.erb
<%= render 'templates/nav' %>
<% if flash[:alert] %>
    <p id="notice"><%= flash[:alert] %></p>
<% end %>
<div id="content">
  <%= render 'templates/genrelist' %>
</div>
<%= render 'templates/audioplayer' %>

app/views/landing/index.html.erb
<%= render 'templates/nav' %>
<% if flash[:alert] %>
    <p id="notice"><%= flash[:alert] %></p>
<% end %>
<div id="content">
  <%= render 'templates/landinglist' %>
</div>
<%= render 'templates/audioplayer' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t('layouts.musicstreamTitle') %></title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:400italic,400,300,700' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body class="<%= yield (:body_class) %>">
<div class="container">
  <%= yield %>
</div>


</body>
</html>

app/views/musics/new.html.erb
<%= render 'templates/nav' %>
<% if flash[:alert] %>
    <p id="notice"><%= flash[:alert] %></p>
<% end %>
<div class="content">
  <%= render 'templates/newmusic' %>
</div>

app/views/templates/_audioplayer.erb
<div class="music-player">
  <div class="sm2-bar-ui flat full-width fixed">

    <div class="bd sm2-main-controls">

      <div class="sm2-inline-texture"></div>
      <div class="sm2-inline-gradient"></div>

      <div class="sm2-inline-element sm2-button-element">
        <div class="sm2-button-bd">
          <a href="#play" class="sm2-inline-button play-pause">Play / pause</a>
        </div>
      </div>

      <div class="sm2-inline-element sm2-inline-status">

        <div class="sm2-playlist">
          <div class="sm2-playlist-target"><ul class="sm2-playlist-bd"><li><b></b></ul></div>
        </div>

        <div class="sm2-progress">
          <div class="sm2-row">
            <div class="sm2-inline-time">0:00</div>
            <div class="sm2-progress-bd">
              <div class="sm2-progress-track">
                <div class="sm2-progress-bar"></div>
                <div class="sm2-progress-ball"><div class="icon-overlay"></div></div>
              </div>
            </div>
            <div class="sm2-inline-duration">0:00</div>
          </div>
        </div>

      </div>

      <div class="sm2-inline-element sm2-button-element sm2-volume">
        <div class="sm2-button-bd">
          <span class="sm2-inline-button sm2-volume-control volume-shade"></span>
          <a href="#volume" class="sm2-inline-button sm2-volume-control">volume</a>
        </div>
      </div>

      <div class="sm2-inline-element sm2-button-element">
        <div class="sm2-button-bd">
          <a href="#prev" title="Previous" class="sm2-inline-button previous">&lt; previous</a>
        </div>
      </div>

      <div class="sm2-inline-element sm2-button-element">
        <div class="sm2-button-bd">
          <a href="#next" title="Next" class="sm2-inline-button next">&gt; next</a>
        </div>
      </div>



      <div class="sm2-inline-element sm2-button-element sm2-menu">
        <div class="sm2-button-bd">
          <a href="#menu" class="sm2-inline-button menu">menu</a>
        </div>
      </div>

    </div>

    <div class="bd sm2-playlist-drawer sm2-element">

      <div class="sm2-inline-texture">
        <div class="sm2-box-shadow"></div>
      </div>

      <!-- playlist content is mirrored here -->

      <div class="sm2-playlist-wrapper">
        <ul class="sm2-playlist-bd">
        </ul>
      </div>

    </div>

  </div>
</div>

app/views/templates/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/templates/_genrelist.erb
# encoding: utf-8

<div class="wrapper">
  <% @music.each do |music| %>
      <div class="music">
        <figure>
          <img src="/assets/images/placeholder.jpg" alt="placeholder"/>
        </figure>
        <div class="music-overlay icon-play">
          <div id="favorites_<%= music.id %>" class="favorite">
            <% if music.ifFavorite %>
                <%= link_to '', favorites_destroy_path(:music_id => music.id), {:class => 'icon-heart active', :remote => true} %>
            <% else %>
                <%= link_to '', favorites_destroy_path(:music_id => music.id), {:class => 'icon-heart', :remote => true} %>
            <% end %>
          </div>
        </div>
        <div class="title">
          <h4><%= music.interpret %></h4>
          <h5><%= music.title %></h5>
        </div>
      </div>
  <% end %>
</div>

app/views/templates/_genres.erb
<div class="wrapper">
  <div class="music">
    <figure>
      <img src="/assets/images/placeholder.jpg" alt="placeholder"/>
    </figure>
      <%= link_to '<div class="music-overlay icon-play"></div>'.html_safe, genre_show_path(:genre_id => 'all'), { :class=>'genre' } %>
    <div class="title">
      <h4><%= link_to 'Alle', genre_show_path(:genre_id => 'all'), { :class=>'genre' } %></h4>
    </div>
  </div>
  <% @genres.each do |genre| %>
      <div class="music">
        <figure>
          <img src="/assets/images/placeholder.jpg" alt="placeholder"/>
        </figure>
        <%= link_to '<div class="music-overlay icon-play"></div>'.html_safe, genre_show_path(:genre_id => genre.id), { :class=>'genre' } %>
        <div class="title">
          <h4><%= link_to genre.title, genre_show_path(:genre_id => genre.id), { :class=>'genre' } %></h4>
        </div>
      </div>
  <% end %>
</div>

app/views/templates/_landinglist.erb
# encoding: utf-8

<div class="wrapper">
    <% @music.each do |music| %>
        <div class="music">
          <figure>
            <img src="/assets/images/placeholder.jpg" alt="placeholder"/>
          </figure>
          <div class="music-overlay icon-play">
            <div id="favorites_<%= music.id %>" class="favorite">
              <%= link_to '',favorites_destroy_path(:music_id => music.id),{ :class =>'icon-heart active', :remote => true } %>
            </div>
          </div>
          <div class="title">
            <h4><%= music.interpret %></h4>
            <h5><%= music.title %></h5>
          </div>
        </div>
    <% end %>
</div>

app/views/templates/_list.erb
# encoding: utf-8

<div class="wrapper">
  <table>
    <% @music.each do |music| %>
        <tr>
          <td class="path" data-path="<%= music.path %>"><i class="icon-play2"></i></td>
          <td class="title"><%= music.title %></td>
          <td class="interpret"><%= music.interpret %></td>
          <td id="favorites_<%= music.id %>" ><%= link_to '',favorites_new_path(:music_id => music.id),{ :class =>'icon-heart', :remote => true } %></td>
        </tr>
    <% end %>
  </table>
</div>

app/views/templates/_nav.erb
  <nav id="nav">
    <header id="header">
      <%= image_tag('/assets/images/logo.png', alt: 'logo') %>
      <h2>Musicstreaming</h2>
      <div class="mobile-close">
        <i class="icon-cross"></i>
      </div>
    </header>
    <ul>
      <li><%= link_to 'Upload', upload_path %></li>
      <li><%= link_to 'Browse', browse_path %></li>
      <li><%= link_to 'Meine Musik', landing_path %></li>
    </ul>
    <div class="search">
      <input type="text" id="search" placeholder="Suche"/>
    </div>
    <div class="logout">
      <li><%= link_to content_tag(:span, 'Ausloggen'), sessions_destroy_path, { :class=>'button' }%></li>
    </div>
    <div class="mobile-open">
      <i class="icon-menu"></i>
    </div>
  </nav>

app/views/templates/_newmusic.erb
<div class="wrapper">
  <div class="upload">
    <h1><%= t('templates.uploadMusicHeading') %></h1>
    <%= form_for @music, :html => {:multipart => true} do |f| %>
        <div class="form">
          <%= f.text_field :interpret, :placeholder => :interpret  %>
          <%= f.text_field :title, :placeholder => :title %>
          <%= f.collection_select :genre_id, Genres.all, :id, :title, :prompt => t('genre') %>
          <%= f.file_field :path %>
        </div>
        <div class="submit">
          <button name="commit" type="submit"><span> <%= t('upload') %></span></button>
        </div>
    <% end %>
  </div>
</div>

app/views/templates/_register.erb
<%= form_for(@user) do |f| %>
    <h1>Register</h1>
    <div class="form">
      <%= f.text_field :username, :placeholder => :username  %>
      <%= f.text_field :email, :placeholder => :email  %>
      <%= f.password_field :password, :placeholder => t('templates.password') %>
      <%= f.password_field :password_confirmation,  :placeholder => t('templates.passwordAgain') %>
    </div>
    <div class="submit">
      <button name="commit" type="submit"><span>Register</span></button>
    </div>
<% end %>

app/views/templates/_settings.erb
#encoding: utf-8
<div class="wrapper">
  <div class="settings">
    <h1> <%= t('templates.settings')%></h1>
    <%= form_for @user do |f| %>
        <div class="form">
          <h2><%= t('templates.changeUser')%> </h2>
          <%= f.text_field :username, :placeholder => :username  %>
          <h2><%= t('templates.changeEmail') %></h2>
          <%= f.text_field :email, :placeholder => :email  %>
          <h2><%= t('templates.changePassword') %></h2>
          <%= f.password_field :password, :placeholder => t('templates.password') %>
          <%= f.password_field :password_confirmation, :placeholder => t('templates.passwordAgain') %>
        </div>
        <div class="submit">
          <button name="commit" type="submit"><span><%= t('templates.saveChanges') %></span></button>
        </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
#encoding: utf-8
<%= render 'templates/nav' %>
<% if flash[:alert] %>
    <p id="notice"><%= flash[:alert] %></p>
<% end %>
<div class="content">
  <%= render 'templates/settings' %>
</div>

app/views/users/new.html.erb
#encoding: utf-8
<% content_for :body_class, 'grey' %>
<div class="login-register register">
  <% if flash[:alert] %>
      <p id="notice"><%= flash[:alert] %></p>
  <% end %>
  <%= render 'templates/register' %>
  <%= link_to t('users.registration'), sessions_new_path %>

</div>